#!/usr/bin/env bun
/**
 * generate-command-stubs.ts
 *
 * Scans the global playbook library and emits thin slash-command stubs so
 * workflows and tasks show up in Claude Code's `/` typeahead menu:
 *
 *   ~/.claude/playbooks/workflows/create-blog-post.md  ->  /wf:create-blog-post
 *   ~/.claude/playbooks/tasks/marketing/publish-...md  ->  /task:publish-blog-post
 *
 * The stubs are DUMB on purpose. They do not inline playbook content (that
 * would be a second copy of the real logic). Each stub only names the playbook
 * and defers resolution to CLAUDE.md's rule: local project copy first, then
 * global. So a project-local override still wins, exactly as it does today.
 *
 * Run it whenever you add, rename, or delete a playbook:
 *
 *   bun ~/.claude/playbooks/scripts/meta/generate-command-stubs.ts
 *
 * No dependencies. Node built-ins only.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, statSync } from 'node:fs'
import { join, basename } from 'node:path'
import { homedir } from 'node:os'

// Marker written into every generated file. Regeneration only deletes files
// that carry it, so a hand-authored command dropped into these dirs survives.
const MARKER = '<!-- generated by generate-command-stubs.ts — do not edit by hand -->'

const PLAYBOOKS = join(homedir(), '.claude', 'playbooks')
const COMMANDS = join(homedir(), '.claude', 'commands')

type Kind = 'workflow' | 'task'

type Source = {
  kind: Kind
  dir: string // 'workflows' | 'tasks' — the library subdir, for the resolution hint
  ns: string // 'wf' | 'task' — the command namespace
  objectiveHeading: string // heading whose first line becomes the description
}

const SOURCES: Source[] = [
  { kind: 'workflow', dir: 'workflows', ns: 'wf', objectiveHeading: '## End State' },
  { kind: 'task', dir: 'tasks', ns: 'task', objectiveHeading: '## Objective' },
]

// -- helpers ---------------------------------------------------------------

/** Recursively collect *.md files under a directory. */
function walk(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      out.push(...walk(full))
    } else if (entry.endsWith('.md')) {
      out.push(full)
    }
  }
  return out
}

/** Real invokable playbook? Skip templates/references (_prefix) and docs. */
function isPlaybook(file: string): boolean {
  const name = basename(file)
  if (name.startsWith('_')) return false
  if (name.startsWith('tasks.')) return false // tasks.README.md, tasks.spec.md
  return true
}

/** First `# ` line, minus the `Workflow:` / `TASK:` prefix. */
function extractTitle(content: string): string {
  for (const line of content.split('\n')) {
    if (line.startsWith('# ')) {
      return line
        .slice(2)
        .replace(/^(Workflow|TASK|Task):\s*/i, '')
        .trim()
    }
  }
  return ''
}

/** First paragraph under the given `## Heading`, wrapped lines joined. */
function extractDescription(content: string, heading: string): string {
  const lines = content.split('\n')
  const start = lines.findIndex((l) => l.trim() === heading)
  if (start === -1) return ''
  const para: string[] = []
  for (let i = start + 1; i < lines.length; i++) {
    const t = lines[i].trim()
    if (!t) {
      if (para.length) break // paragraph ended
      continue // skip blank lines before the paragraph
    }
    if (t.startsWith('#')) break // next heading, no paragraph found
    para.push(t)
  }
  return para.join(' ')
}

/** Cap at ~110 chars on a word boundary. Menu descriptions stay one line. */
function truncate(s: string, max = 110): string {
  if (s.length <= max) return s
  const cut = s.slice(0, max)
  const lastSpace = cut.lastIndexOf(' ')
  return (lastSpace > 40 ? cut.slice(0, lastSpace) : cut).trim() + '…'
}

/** Quote a value for YAML frontmatter safely. */
function yamlQuote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}

function buildStub(opts: { name: string; kind: Kind; dir: string; title: string; description: string }): string {
  const { name, kind, dir, title, description } = opts
  const desc = truncate(description || title)
  return `---
description: ${yamlQuote(desc)}
argument-hint: [input]
---
${MARKER}

Run the **${title || name}** ${kind} playbook (\`${name}\`).

Resolve the file per CLAUDE.md (local project first, then global):
1. \`playbooks/${dir}/**/${name}.md\` in the current project
2. \`~/.claude/playbooks/${dir}/**/${name}.md\`

First hit wins. Read the resolved file in full and execute it, treating everything below as its input. If neither path resolves, say so instead of guessing.

---
$ARGUMENTS
`
}

/** Delete only generator-owned *.md in a dir, leaving hand-authored ones. */
function clearGenerated(dir: string): void {
  let entries: string[]
  try {
    entries = readdirSync(dir)
  } catch {
    return // dir does not exist yet
  }
  for (const entry of entries) {
    if (!entry.endsWith('.md')) continue
    const full = join(dir, entry)
    try {
      if (readFileSync(full, 'utf8').includes(MARKER)) rmSync(full)
    } catch {
      /* ignore */
    }
  }
}

// -- main ------------------------------------------------------------------

let total = 0
const collisions: string[] = []

for (const src of SOURCES) {
  const srcDir = join(PLAYBOOKS, src.dir)
  const outDir = join(COMMANDS, src.ns)
  mkdirSync(outDir, { recursive: true })
  clearGenerated(outDir)

  const seen = new Set<string>()
  const files = walk(srcDir).filter(isPlaybook).sort()

  for (const file of files) {
    const name = basename(file, '.md')
    if (seen.has(name)) {
      collisions.push(`/${src.ns}:${name} (duplicate basename, second one skipped: ${file})`)
      continue
    }
    seen.add(name)

    const content = readFileSync(file, 'utf8')
    const stub = buildStub({
      name,
      kind: src.kind,
      dir: src.dir,
      title: extractTitle(content),
      description: extractDescription(content, src.objectiveHeading),
    })
    writeFileSync(join(outDir, `${name}.md`), stub)
    total++
    console.log(`  /${src.ns}:${name}`)
  }
}

console.log(`\nGenerated ${total} command stub(s) under ${COMMANDS}/{wf,task}/`)
if (collisions.length) {
  console.log('\nName collisions (flattening dropped these — rename to fix):')
  for (const c of collisions) console.log(`  - ${c}`)
}
